theme: minima
title: Norsk nettverk for digital humaniora og kulturinstitusjoner
author:
  name: Camilla Soelseth
  email: your-email@domain.com
description: DHKI - Norsk nettverk for digital humaniora og kulturinstitusjoner

